# Generated by Django 4.2 on 2025-10-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=128, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('audio_file', models.FileField(upload_to='recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
