# Generated by Django 4.2 on 2025-10-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='is_drone_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
