# Generated by Django 4.2 on 2025-10-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_recording_is_drone_suspicious"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recording",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
